### ISSUE TITLE
Less reload

### ISSUE THREAD

**Issue by Torone** [dstroot/skeleton#35]
Hi,

Thanks for your work with Skeleton.

I was just trying it and I found an issue: every time I do some changes on the less files I should restart Gulp to see the changes on the browser.
There is a fastest way to see these changes in real time?

Best

**Comment by Torone** [comment]
Hi,

Well, I'm back to the code to how to fix it and I found a small issue:

If I add a new `.less` file and I import it in the `main.less` file every changes I do in the new one it doesn't trigger `gulp watch` because it is listening only the files added in the paths model. So to reload it I should fake save the `main.less` file.

It would be better to listen all the less files `gulp.watch('less/**/*.less', ['styles']);`.
Same for the Javascript files (if someone need to add new ones).

It fixed all my problems, I hope it will help to improve it always better this great project.

Best

**Comment by dstroot** [comment]
Thanks!
