### ISSUE TITLE
Can we use Cloudinary Images?

### ISSUE THREAD

**Issue by pepcha** [dstroot/skeleton#37]
Hi Dan Stroot, 

Thank you for creating skeleton project. I am using this as a basis for one of the major projects. I am wondering if we can integrate cloudinary like keystoneJs into this application?

Thanks
lavanya

**Comment by dstroot** [comment]
Sure - if you host your images on Cloudinary you just point to them in your img tags.  Otherwise I'm not sure I understand your question.  

Cheers!

**Comment by pepcha** [comment]
Thanks for the reply.
Sorry for not being clear on my question.

I am trying to upload profile images instead of using gravatar and planning to use cloudinary to save all the images. 

Was wondering if we can use something like that or if there is anything that you would like to suggest.

Thanks
Lavanya

**Comment by dstroot** [comment]
I like the idea of uploading your own avatar - if I was building it out I would probably us AWS S3 as storage.  However Cloudinary gives you some flexibility on how it creates image sizes on the fly.  I see no reason why it should not work.  Best of luck.
