### ISSUE TITLE
Removing node-foursquare breaks console/debug logging.

### ISSUE THREAD

**Issue by jbogatay** [dstroot/skeleton#39]
Commenting and/or removing the 

    require('node-foursquare')

in api.js breaks the app.   The console colors are no longer available.

    debug('listening on port ' + app.get('port').toString().green.bold);
                                                               ^
    TypeError: Cannot read property 'bold' of undefined

**Comment by dstroot** [comment]
Yes, should be an explicit dependency.  Try:

```
var colors = require('colors');
```

**Comment by jbogatay** [comment]
Yup :+1:
